### ISSUE TITLE
Add Unwrap?

### ISSUE THREAD

**Issue by matthijskooijman** [go-errors/errors#14]
Would it make sense to add an `Unwrap()` function to this library? I have a usecase where I need to check the type of the underlying error, which (AFAICS) `Is()` cannot do. I can access the `Err` field of an `errors.Error`, but that requires having a `*Error` instead of an `error`, which AFAIU isn't the intended way to return (wrapped) errors.

Such a function could simply look like:

```
func Unwrap(err error) error {
        switch e := err.(type) {
                case *errors.Error:
                        return e.Err
                default:
                        return err
        }
}
```

**Comment by titouanfreville** [comment]
I don't think this is still relevant with latest go version and fix of go-errors Is method in v1.1.0
