### ISSUE TITLE
Test fails due to stack traces

### ISSUE THREAD

**Issue by rockstorm101** [go-errors/errors#21]
Hi, tests are failing again since go 1.11.

Maybe @gabrielf could come up again with a solution for this? :P

Thanks a lot.

```
$ go version
go version go1.11.5 linux/amd64

$ go test -vet=off -v -p 4 github.com/go-errors/errors
=== RUN   TestStackFormat
--- FAIL: TestStackFormat (0.00s)
    error_test.go:33: Stack trace does not contain source line: 'a: b(5)'
    error_test.go:34: /build/golang-github-go-errors-errors-1.0.1/obj-x86_64-linux-gnu/src/github.com/go-errors/errors/error_test.go:21 (0x4f5f35)
        	TestStackFormat.func1: e, expected := Errorf("hi"), callers()
        /usr/lib/go-1.11/src/runtime/asm_amd64.s:522 (0x455b3b)
        	call32: CALLFN(·call32, 32)
        /usr/lib/go-1.11/src/runtime/panic.go:513 (0x429df9)
        	gopanic: reflectcall(nil, unsafe.Pointer(d.fn), deferArgs(d), uint32(d.siz), uint32(d.siz))
        /build/golang-github-go-errors-errors-1.0.1/obj-x86_64-linux-gnu/src/github.com/go-errors/errors/error_test.go:245 (0x4f38ff)
        	TestStackFormat: panic('a')
        /usr/lib/go-1.11/src/testing/testing.go:827 (0x4b573f)
        	tRunner: fn(t)
        /usr/lib/go-1.11/src/runtime/asm_amd64.s:1333 (0x4576d1)
        	goexit: BYTE	$0x90	// NOP
```

Originally reported in Debian [[1]] by Adrian Bunk.

[1]: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=918619#5

**Comment by rockstorm101** [comment]
Hi, is there any update on this? Maybe even a "Won't Fix"?

**Comment by ConradIrwin** [comment]
Hey Rock! We’re using an internal copy of this right now — would love a pull request if you feel up for it,

Conrad

**Comment by rockstorm101** [comment]
Hi @ConradIrwin, I would love a PR on this too :P.

In all honesty, I've tried and failed. I clearly lack the knowledge here. If this is going to be a "won't-fix" I'll have to propose ignoring this particular test on the Debian package, which is something I'm currently reluctant to do.

Thanks for answering anyway.

**Comment by anthonyfok** [comment]
For some reasons, this test seems to pass with Go 1.12, but continues to fail with Go 1.11.

Tested with go1.12.7 and go1.11.12.

**Comment by rockstorm101** [comment]
> For some reasons, this test seems to pass with Go 1.12, but continues to fail with Go 1.11.

Great news. Thanks for the fix in Debian.

**Comment by anthonyfok** [comment]
> > For some reasons, this test seems to pass with Go 1.12, but continues to fail with Go 1.11.
> 
> Great news. Thanks for the fix in Debian.

You're very welcome.  I needed the fix myself anyway.  :-)

The stack trace test seems very flaky; or, rather, Go sometimes generate unpredictable stack trace?  I am seeing different stack trace outputs with gccgo-8 and gccgo-9, for example, on amd64 vs mipsel.

* gccgo-8 on amd64: FAIL.
* gccgo-9 on amd64: PASS.  Yay!
* gccgo-8 on amd64: TestStackFormat passes, but TestNew fails:

```
--- FAIL: TestNew (0.00s)
	error_test.go:81: Stack didn't match
	error_test.go:82: First entry PC diff to large (36)
		Actual stack trace:
		/home/foka/golang-github-go-errors-errors-1.0.1/error_test.go:78 (0x5559d307)
			__home_foka_golang_github_go_errors_errors_1_0_1.TestNew
		../../../src/libgo/go/testing/testing.go:777 (0x77924fbb)
			testing.tRunner
		../../../src/libgo/go/runtime/proc.go:1167 (0x778a2293)
			runtime.kickoff
		
		Expected stack trace:
		/home/foka/golang-github-go-errors-errors-1.0.1/error_test.go:78 (0x5559d32b)
			__home_foka_golang_github_go_errors_errors_1_0_1.TestNew
		../../../src/libgo/go/testing/testing.go:777 (0x77924fbb)
			testing.tRunner
		../../../src/libgo/go/runtime/proc.go:1167 (0x778a2293)
			runtime.kickoff
```

* gccgo-9 on mipsel:

```
# _/home/foka/golang-github-go-errors-errors-1.0.1 [_/home/foka/golang-github-go-errors-errors-1.0.1.test]
go1: internal compiler error: in mangled_name, at go/gofrontend/names.cc:559
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-9/README.Bugs> for instructions.
FAIL	_/home/foka/golang-github-go-errors-errors-1.0.1 [build failed]
```

Oh well...

**Comment by rockstorm101** [comment]
> The stack trace test seems very flaky; or, rather, Go sometimes generate unpredictable stack trace? I am seeing different stack trace outputs with gccgo-8 and gccgo-9, for example, on amd64 vs mipsel.

Traces look the same but for that number at the end (the program counter?):
`/home/foka/golang-github-go-errors-errors-1.0.1/error_test.go:78 (0x5559d307)`
`/home/foka/golang-github-go-errors-errors-1.0.1/error_test.go:78 (0x5559d32b)`

So maybe the stack comparison should be relaxed to allow such mismatch? I'm honestly too lost here.

**Comment by anthonyfok** [comment]
> So maybe the stack comparison should be relaxed to allow such mismatch? I'm honestly too lost here.

Sorry, I might have overemphasized and missed the main point.  Although the test is indeed a bit flaky, or rather, Go's stack trace does not seem to produce identical output, I wouldn't worry too much as long as, for instance, it builds fine on Debian buildd machine and passes the automated tests:

* https://tracker.debian.org/pkg/golang-github-go-errors-errors
* https://buildd.debian.org/status/package.php?p=golang-github-go-errors-errors
* https://ci.debian.net/packages/g/golang-github-go-errors-errors/

where both the buildd and the automated tests runs only on amd64 with the standard Go compiler (gc) and never with MIPS or gccgo.  Furthermore, this particular test really doesn't affect the usability of this Go library, so all is fine now IMHO.  :-)
