### ISSUE TITLE
PR #33 broke compatibility

### ISSUE THREAD

**Issue by dsoprea** [go-errors/errors#34]
Yeah, so `Wrap()` used to return `*Error` and now returns `error`. This will break a lot of people. Regardless of the merits of this change, in principal, this was a backwards-incompatible change that should not have been made. Now, your package is breaking all of my packages upon upgrade, and all of the outside projects that are consuming them, and doubtless more well beyond just my scope.

https://github.com/go-errors/errors/commit/2ae1e4450826c9fecb6d5eb82b216f93f5808770

Error output (with a `replace` clause in the go.mod):

```
../go-logging/v2/log.go:356:14: cannot use "github.com/go-errors/errors".Wrap(err, 2) (type error) as type *"github.com/go-errors/errors".Error in assignment: need type assertion
../go-logging/v2/log.go:483:20: cannot use "github.com/go-errors/errors".Wrap(err, 1) (type error) as type *"github.com/go-errors/errors".Error in return argument: need type assertion
../go-logging/v2/log.go:489:20: cannot use "github.com/go-errors/errors".Wrap(err, 1) (type error) as type *"github.com/go-errors/errors".Error in return argument: need type assertion
```

I would request that you revert this change, and move this feature, if still required, to the next major release in order to maintain API compatibility with all current integrations (per the [Go Compatibility Promise](https://golang.org/doc/go1compat)).

**Comment by ConradIrwin** [comment]
Hey @dsoprea!

I'm sorry about that – I didn't consider the impact this would have on people using libraries that transitively depend on this! 

(I had erroneously assumed that people would either have a version in `go.mod` already in which case they'd continue to see the old behaviour until they opted in to an upgrade, or they would be adding `errors` to their mod file for the first time in which case they'd get the better behaviour from day one. This is mostly true, but in hindsight is obviously broken if someone depends both on errors directly, and also a library that depends on errors; because they can chose to upgrade errors without the knowledge of the library author).

I'll revert for now.

**Comment by dsoprea** [comment]
As well as if other maintainers just do a general update. They're blocked from general updates because of a dependency (you) of a dependency (my logging package) of a dependency (my package that they're using) of a dependency (their package). The whole chain breaks down. In this case, he was meaning to just update my package and was updating everything, but, still, I don't like that a deeper requirements of my project, several times removed from his project, is preventing him from conducting his business.

I made the change to adopt `error` versus `*errors.Error` because I wasn't sure if you'd respond. However, because a) those values are not a completely internal semantic of go-logging (the wrapped-error values can be returned directly and captured by an external caller), and b) the loss of type-safety (because we're now often passing around `error` rather than `*errors.Error`) means that the stacktrace printouts could potentially fail if accidentally called for unwrapped errors. So, I need to very thoroughly test it and all of its integrations and add some panics where the stacktrace is expected to be available but may no longer be, and I'm not prepared to do that at this moment, especially in the context of actively failing integrations. Better to just revert (as you have already done).

Honestly, I'm not a huge fan of the above. I would strongly encourage you to push it into the next release, which I will probably never adopt. I don't have an issue with the way it was already working.

Thanks for responding/reacting so quickly.

The revert, for the record: https://github.com/go-errors/errors/commit/b28c3b08d7afb2c96fb4c9cf7d9410bb8a4088d6

**Comment by dsoprea** [comment]
Confirmed resolved.

**Comment by ConradIrwin** [comment]
Thanks for the reply (I also did not realize that `go get -u` would update transitive dependencies), and sorry again for the frustration.
