### ISSUE TITLE
Why keep cover.out file in the repo?

### ISSUE THREAD

**Issue by RainbowMango** [go-errors/errors#38]
The file [cover.out](https://github.com/go-errors/errors) seems a test coverage file. 

Don't know why it keeps in the repo.

But it might be some trouble when people vendor this package and with a `.gitignore` file in which the `*.out` file is ignored.

**Comment by ConradIrwin** [comment]
Thanks for spotting!

**Comment by RainbowMango** [comment]
Hi @ConradIrwin ,
Thanks for your quick response. 
Another question is would you like to cut a new release, since the latest release is about one year ago.
