### ISSUE TITLE
Functions Join and Unwrap

### ISSUE THREAD

**Issue by lovromazgon** [go-errors/errors#42]
Similar to how this library already provides `As` and `Is`, it would be nice also to provide [`Join`](https://pkg.go.dev/errors#Join) and [`Unwrap`](https://pkg.go.dev/errors#Unwrap), simply by delegating to the stdlib implementations. This way there would no longer be a need to import stdlib `errors` and we could avoid the naming conflict when both packages are imported.

Let me know if you would consider adding this, I can open a PR.

**Comment by ConradIrwin** [comment]
Absolutely, please do!

**Comment by lovromazgon** [comment]
@ConradIrwin do you plan to create a release anytime soon? We'd like to use it, although it would be nice if we could pin the dependency to a proper version.

**Comment by ConradIrwin** [comment]
@ConradIrwin <https://github.com/ConradIrwin> do you plan to create a
release anytime soon? We'd like to use it, although it would be nice if we
could pin the dependency to a proper version.


Sorry for the delay, 1.5.0 is hot off the press!

**Comment by lovromazgon** [comment]
Thank you!
