### ISSUE TITLE
Create annotated tags for releases

### ISSUE THREAD

**Issue by benma** [go-errors/errors#8]
Hi

It would be great if you tagged the current HEAD with v1.0.0, and in the future, occasionally bump the version and make new tags with new releases. I suggest using the semver.org versioning scheme, where you have major.minor.patch, and you bump the major for incompatible changes and the minor for compatible changes to the API.

**Comment by bdouxx** [comment]
hi,

go-errors is used by to build arduino-builder https://github.com/arduino/arduino-builder

Can you create a tag in order to simplify build on linux distribution?

**Comment by ConradIrwin** [comment]
done!
